### ISSUE TITLE
Migrate charts to common v3

### ISSUE THREAD

**Issue by bjw-s** [k8s-at-home/charts#942]
# Details

The following charts need to be upgraded to the latest version of the common library. Since this is a mostly manual task, we'll track the progress here 

#### To Do:

- [ ] baikal (#1077)
- [ ] blocky (#1077)
- [ ] comcast (#1077)
- [ ] gollum (#1077)
- [ ] jetbrains-projector (#1077)
- [ ] kanboard (#1077)
- [ ] leaf2mqtt (#1011)
- [ ] unpackerr (#1077)
- [ ] uptimerobot-prometheus (#1077)
- [ ] valheim (#1077)
- [ ] vikunja (#1077)
- [ ] wallabag (#1077)
- [ ] whoogle (#1077)
- [ ] wikijs (#1077)
- [ ] xbackbone (#1077)
- [ ] youtubedl-material (#1077)

#### Done:

- [x] ~adguard-home (#952)~
- [x] ~airsonic (#941)~
- [x] ~alertmanager-bot (#954)~
- [x] ~appdaemon (#1070)~
- [x] ~bazarr (#969)~
- [x] ~booksonic-air (#989)~
- [x] ~bookstack (#950)~
- [x] ~calibre (#1004)~
- [x] ~calibre-web (#973)~
- [x] ~deconz (#1017)~
- [x] ~deluge (#981)~
- [x] ~dizquetv (#984)~
- [x] ~dnsmadeeasy-webhook (#986)~
- [x] ~dsmr-reader (#968)~
- [x] ~duplicati (#987)~
- [x] ~emby (#961)~
- [x] ~esphome (#988)~
- [x] ~flaresolverr (#990)~
- [x] ~flood (#996)~
- [x] ~focalboard (#997)~
- [x] ~founderyvtt (#948)~
- [x] ~freshrss (#998)~
- [x] ~gaps (#999)~
- [x] ~gonic (#1000)~
- [x] ~grocy (#1001)~
- [x] ~haste-server (#947)~
- [x] ~healthchecks (#1006)~
- [x] ~heimdall (#1002)~
- [x] ~home-assistant (#964)~
- [x] ~homebridge (#1005)~
- [x] ~homer (#1007)~
- [x] ~hyperion-ng (#1008)~
- [x] ~icantbelieveitsnotvaletudo (#1009)~
- [x] ~intel-gpu-plugin (#966)~
- [x] ~jackett (#992)~
- [x] ~jellyfin (#977)~
- [x] ~joplin-server (#1016)~
- [x] ~lazylibrarian (#1029)~
- [x] ~librespeed (#1030)~
- [x] ~lidarr (#969)~
- [x] ~lychee (#1035)~
- [x] ~magic-mirror (#1063)~
- [x] ~mealie (#967)~
- [x] ~miniflux (#1060)~
- [x] ~modem-stats (#1063)~
- [x] ~monica (#1063)~
- [x] ~mosquitto (#957)~
- [x] ~multus (#1040)~
- [x] ~mylar (#1063)~
- [x] ~navidrome (#1063)~
- [x] ~neolink (#1063)~
- [x] ~network-ups-tools (#1067)~
- [x] ~node-red (#1067)~
- [x] ~nzbget (#975)~
- [x] ~nzbhydra2 (#1044)~
- [x] ~octoprint (#976)~
- [x] ~omada-controller (#1067)~
- [x] ~ombi (#1067)~
- [x] ~openemr (#960)~
- [x] ~organizr (#1067)~
- [x] ~overseerr (#1044)~
- [x] ~owncast (#1067)~
- [x] ~paperless (#1039)~
- [x] ~photoprism (#980)~
- [x] ~piaware (#1067)~
- [x] ~plex (#963)~
- [x] ~pod-gateway (#944)~
- [x] ~pretend-youre-xyzzy (#1067)~
- [x] ~promcord (#1067)~
- [x] ~prometheus-nut-exporter (#1067)~
- [x] ~protonmail-bridge (#1067)~
- [x] ~prowlarr (#969)~
- [x] ~pyload (#1067)~
- [x] ~qbittorrent (#978)~
- [x] ~radarr (#969)~
- [x] ~readarr (#969)~
- [x] ~recipes (#1067)~
- [x] ~reg (#958)~
- [x] ~resilio-sync (#1067)~
- [x] ~rtorrent-flood (#1050)~
- [x] ~sabnzbd (#1044)~
- [x] ~samba (#1070)~
- [x] ~searx (#1070)~
- [x] ~ser2sock (#1070)~
- [x] ~sharry (#1070)~
- [x] ~shlink (#959)~
- [x] ~smarter-device-manager (#1070)~
- [x] ~sonarr (#969)~
- [x] ~speedtest-exporter (#1070)~
- [x] ~stash (#1044)~
- [x] ~statping (#1070)~
- [x] ~syncthing (#1070)~
- [x] ~tautulli (#1044)~
- [x] ~tdarr (#1070)~
- [x] ~teedy (#1070)~
- [x] ~teslamate (#1070)~
- [x] ~thelounge (#946)~
- [x] ~traccar (#1044)~
- [x] ~transmission (#1028)~
- [x] ~truecommand (#1070)~
- [x] ~tt-rss (#986)~
- [x] ~tvheadend (#1044)~
- [x] ~unifi-poller (#1043)~
- [x] ~vaultwarden (#949)~
- [x] ~xteve (#1044)~
- [x] ~zalando-postgres-cluster (#986)~
- [x] ~zigbee2mqtt (#956)~
- [x] ~zwave2mqtt~ (deprecated)
- [x] ~zwavejs2mqtt (#1014)~

**Comment by nicholaswilde** [comment]
I haven't looked yet, but does the template chart need to be updated? I use the template as a base/example when updating charts.

**Comment by bjw-s** [comment]
> I haven't looked yet, but does the template chart need to be updated? I use the template as a base/example when updating charts.

Good call! I'll do that one right now :)

**Comment by bjw-s** [comment]
@nicholaswilde The template has been updated 👍

**Comment by angelnu** [comment]
@bjw-s - just checking - the expectation is that each of the mainteiners update theirs with their PR and then check the box, right?

Beyond the removal of the additionalVolumes - anything else we need to pay attention to?

**Comment by bjw-s** [comment]
> @bjw-s - just checking - the expectation is that each of the mainteiners update theirs with their PR and then check the box, right?

Not necessarily, anyone can pick up any chart. Ideally it would be the/a maintainer, but they can always chime in on the PR.

> Beyond the removal of the additionalVolumes - anything else we need to pay attention to?

`service` and `ingress` now have a `main` subkey now to handle the main Service and Ingress

**Comment by angelnu** [comment]
Thanks for the 3.0.1 - it enabled me to update the pod-gateway. Nice rework!

Will do my other charts next and then will see if I can help with the rest.

**Comment by bjw-s** [comment]
Silly Github autoclosing.... I guess that will happen more frequently on this one 😓

**Comment by onedr0p** [comment]
Good work everyone. closing this issue :)
